project:
  name: ""
  created_date: ""
  last_modified: ""
  path: ""
  version: "0.1"

settings:
  image_folder: images
  log_folder: logs
  settings_folder: settings
  result_folder: results

window_size_windows:
  window_width: 1500
  window_height: 1100
  image_widget_width: 899
  log_widget_width: 599
  
window_size_mac:
  window_width: 1000
  window_height: 800
  image_widget_width: 599
  log_widget_width: 399

image:
  name: ""
  size: 0
  width: 0
  height: 0
  format: ""
  path: ""

tool:
  color: "#FF0000"
  color_name: "Red"

log_widget:
  "checkbox": true
  "#": true
  "X": true
  "Y": true
  "Width": true
  "Height": true
  "Well": true
  "Color": true
  "Note": true
  "Delete": true
  widths: [20, 40, 40, 40, 40, 40, 50, 115, 144, 24]
